version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
